// src/app/mentions-legales/mentions-legales.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-mentions-legales',
  templateUrl: './mentions-legales.component.html',
  styleUrls: ['./mentions-legales.component.css']
})
export class MentionsLegalesComponent {

  constructor () { }

}

<div class="container is-max-desktop">
  <h1 class="title is-1 has-text-centered">MENTIONS LÉGALES</h1>
  <h1 class="subtitle is-2 pt-6 has-text-centered">IDENTITÉ</h1>
  <p class="has-text-justified">
    <b>Nom du site Web :</b> topmaths<br>
    <b>Adresse :</b> https://topmaths.fr<br>
    <b>Propriétaire :</b> Guillaume VALMONT<br>
    <b>Responsable de publication :</b> Guillaume VALMONT<br>
    <b>Conception et réalisation :</b> Guillaume VALMONT<br>
    <b>Hébergement :</b> OVH, 2 rue Kellermann, 59100 ROUBAIX
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">INFORMATIONS</h1>
  <p class="has-text-justified">
    Les informations et documents du site sont présentés à titre indicatif, n’ont pas de caractère exhaustif et ne peuvent engager la responsabilité du propriétaire du site.
    <br><br>
    Le propriétaire du site ne peut être tenu responsable des dommages directs et indirects consécutifs à l’accès au site.
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">PROPRIÉTÉ INTELLECTUELLE</h1>
  <p class="has-text-justified">
    Le contenu du site est sous licence <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr" target="_blank" rel="noopener noreferrer">CC-BY-SA 4.0</a>.<br>
    Le <a href="https://github.com/gvalmont/topmaths" target="_blank" rel="noopener noreferrer"> code source du site</a> est sous licence <a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank" rel="noopener noreferrer">AGPL 3.0</a>. 
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">LIENS</h1>
  <p class="has-text-justified">
    Le propriétaire du site décline toute responsabilité et n’est pas engagé par le référencement via des liens hypertextes, de ressources tierces présentes sur Internet, tant en ce qui concerne leur contenu que leur pertinence.
    <br><br>
    Le propriétaire du site autorise les liens hypertextes vers l’une des pages de ce site, à condition que ceux-ci ouvrent une nouvelle fenêtre et soient présentés de manière non équivoque afin d’éviter tout risque de confusion entre le site citant et le propriétaire du site ainsi que toute présentation tendancieuse, ou contraire aux lois en vigueur.
    <br><br>
    Le propriétaire du site se réserve le droit de demander la suppression d’un lien s’il estime que le site source ne respecte pas les règles ainsi définies.
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">CONFIDENTIALITÉ</h1>
  <p class="has-text-justified">
    Tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant (notamment les emails envoyés dans le formulaire de contact), en adressant sa demande, accompagnée d’une preuve d’identité, par courriel à contact[at]topmaths.fr.
<br>
Le site ne recueille pas d’informations personnelles et n’est pas assujetti à déclaration à la CNIL.
<br>
Voir également la page <a routerLink="/politique-de-confidentialite" routerLinkActive="active">Politique de confidentialité</a>.
  </p>
</div>

// src/topmaths/components/MentionsLegales.svelte
<script lang="ts">
  import { goVue } from '../services/outils'

</script>

<div class="container is-max-desktop">
  <h1 class="title is-1 has-text-centered">MENTIONS LÉGALES</h1>
  <h1 class="subtitle is-2 pt-6 has-text-centered">IDENTITÉ</h1>
  <p class="has-text-justified">
    <b>Nom du site Web :</b> topmaths<br />
    <b>Adresse :</b> https://topmaths.fr<br />
    <b>Propriétaire :</b> Guillaume VALMONT<br />
    <b>Responsable de publication :</b> Guillaume VALMONT<br />
    <b>Conception et réalisation :</b> Guillaume VALMONT<br />
    <b>Hébergement :</b> Hodi SAS - 14 rue Pasteur - 97400 Saint-Denis - La Réunion
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">INFORMATIONS</h1>
  <p class="has-text-justified">
    Les informations et documents du site sont présentés à titre indicatif,
    n’ont pas de caractère exhaustif et ne peuvent engager la responsabilité du
    propriétaire du site.
    <br /><br />
    Le propriétaire du site ne peut être tenu responsable des dommages directs et
    indirects consécutifs à l’accès au site.
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">PROPRIÉTÉ INTELLECTUELLE</h1>
  <p class="has-text-justified">
    Le contenu du site est sous licence <a
      href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr"
      target="_blank"
      rel="noopener noreferrer">CC-BY-SA 4.0</a
    >.<br />
    Le
    <a
      href="https://forge.aeif.fr/gvalmont/topmathalea"
      target="_blank"
      rel="noopener noreferrer"
    >
      code source du site</a
    >
    est sous licence
    <a
      href="https://www.gnu.org/licenses/agpl-3.0.html"
      target="_blank"
      rel="noopener noreferrer">AGPL 3.0</a
    >.
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">LIENS</h1>
  <p class="has-text-justified">
    Le propriétaire du site décline toute responsabilité et n’est pas engagé par
    le référencement via des liens hypertextes, de ressources tierces présentes
    sur Internet, tant en ce qui concerne leur contenu que leur pertinence.
    <br /><br />
    Le propriétaire du site autorise les liens hypertextes vers l’une des pages de
    ce site, à condition que ceux-ci ouvrent une nouvelle fenêtre et soient présentés
    de manière non équivoque afin d’éviter tout risque de confusion entre le site
    citant et le propriétaire du site ainsi que toute présentation tendancieuse,
    ou contraire aux lois en vigueur.
    <br /><br />
    Le propriétaire du site se réserve le droit de demander la suppression d’un lien
    s’il estime que le site source ne respecte pas les règles ainsi définies.
  </p>
  <h1 class="subtitle is-2 pt-6 has-text-centered">CONFIDENTIALITÉ</h1>
  <p class="has-text-justified">
    Le site ne recueille pas d’informations personnelles et n’est pas assujetti à
    déclaration à la CNIL.
    <br />
    Voir également la page
    <button
      class="has-text-link"
      on:click={(event) => goVue(event, 'politique-de-confidentialite')}
      >Politique de confidentialité</button
    >.
  </p>
</div>
