// src/app/objectif/objectif.component.ts
import { ViewportScroller } from '@angular/common'
import { Component, OnDestroy, OnInit } from '@angular/core'
import { ActivatedRoute, Router } from '@angular/router'
import { Objectif, Video, Exercice } from '../services/modeles/objectifs'
import { Title } from '@angular/platform-browser'
import { DataService } from '../services/data.service'
import { Subscription } from 'rxjs'
import { Sequence } from '../services/modeles/sequences'
import { StorageService } from '../services/storage.service'
import { PanierItem } from '../services/modeles/panier'
import { environment } from 'src/environments/environment'
import { OutilsService } from '../services/outils.service'

@Component({
  selector: 'app-objectif',
  templateUrl: './objectif.component.html',
  styleUrls: ['./objectif.component.css']
})
export class ObjectifComponent implements OnInit, OnDestroy {
  reference: string
  niveau: string
  titre: string
  rappelDuCoursHTML: string
  rappelDuCoursImage: string
  rappelDuCoursInstrumenpoche: string
  videos: Video[]
  exercices: Exercice[]
  lienExercices: string
  sequences: Sequence[]
  infosModale: [string[], string, Date]
  dataMAJSubscription: Subscription
  tousLesExercicesSontDansLePanier: boolean

  // eslint-disable-next-line no-unused-vars
  constructor (private activatedRoute: ActivatedRoute, private dataService: DataService, public router: Router, private viewportScroller: ViewportScroller, private titleService: Title, public storageService: StorageService, private outilsService: OutilsService) {
    this.reference = ''
    this.niveau = ''
    this.titre = ''
    this.rappelDuCoursHTML = ''
    this.rappelDuCoursImage = ''
    this.rappelDuCoursInstrumenpoche = ''
    this.videos = []
    this.exercices = []
    this.lienExercices = ''
    this.sequences = []
    this.infosModale = [[], '', new Date() ]
    this.dataMAJSubscription = new Subscription
    this.tousLesExercicesSontDansLePanier = false
  }

  ngOnInit (): void {
    this.viewportScroller.scrollToAnchor('titre')
    this.surveillerChangementsDeReference()
    this.surveillerLeChargementDesDonnees()
  }

  ngOnDestroy () {
    this.dataMAJSubscription.unsubscribe()
  }

  surveillerChangementsDeReference () {
    this.activatedRoute.params.subscribe(params => {
      this.reference = params.reference
      if (this.lesDonneesSontChargees()) this.MAJPage()
    })
  }

  surveillerLeChargementDesDonnees () {
    this.dataMAJSubscription = this.dataService.dataMAJ.subscribe(valeurModifiee => {
      if (valeurModifiee === 'niveauxObjectifs' || valeurModifiee === 'niveauxSequences') {
        if (this.lesDonneesSontChargees()) this.MAJPage()
      }
    })
  }

  lesDonneesSontChargees () {
    return this.dataService.niveauxObjectifs.length > 0 && this.dataService.niveauxSequences.length > 0
  }

  MAJPage () {
    const objectif: Objectif = this.getObjectif()
    this.sequences = this.getSequences()
    this.niveau = objectif.reference.slice(0, 1) + 'e'
    this.MAJProprietes(objectif)
  }

  getObjectif () {
    for (const niveau of this.dataService.niveauxObjectifs) {
      for (const theme of niveau.themes) {
        for (const sousTheme of theme.sousThemes) {
          for (const objectif of sousTheme.objectifs) {
            if (objectif.reference === this.reference) {
              return objectif
            }
          }
        }
      }
    }
    return new Objectif('', '', 0, '', '', '', [], [])
  }

  getSequences () {
    const listeDesSequences = []
    for (const niveau of this.dataService.niveauxSequences) {
      for (const sequence of niveau.sequences) {
        for (const objectif of sequence.objectifs) {
          if (objectif.reference === this.reference) {
            listeDesSequences.push(sequence)
          }
        }
      }
    }
    return listeDesSequences
  }

  MAJProprietes (objectif: Objectif) {
    this.titre = `${objectif.reference} : ${objectif.titre}`
    this.titleService.setTitle(this.titre)
    this.MAJRappelDuCours(objectif)
    this.MAJVideos(objectif)
    this.MAJLienExercices(objectif)
    this.MAJExercices(objectif)
    this.MAJLienTelechargement(objectif.reference, 'entrainement')
    this.MAJAffichageSequences()
    if (this.storageService.modeEnseignant) this.MAJLienTelechargement(objectif.reference, 'test')
  }

  MAJRappelDuCours (objectif: Objectif) {
    this.rappelDuCoursHTML = objectif.rappelDuCoursHTML
    if (objectif.rappelDuCoursImage === '') {
      this.rappelDuCoursImage = ''
    } else {
      this.rappelDuCoursImage = '../assets/img/' + objectif.rappelDuCoursImage
    }
    if (objectif.rappelDuCoursInstrumenpoche === '' || typeof objectif.rappelDuCoursInstrumenpoche === 'undefined') {
      this.rappelDuCoursInstrumenpoche = ''
    } else {
      this.rappelDuCoursInstrumenpoche = objectif.rappelDuCoursInstrumenpoche
    }
  }

  MAJVideos (objectif: Objectif) {
    this.videos = []
    for (const video of objectif.videos) {
      if (video.slug !== '') {
        let lienVideo: string
        if (video.slug.slice(0, 4) === 'http') {
          lienVideo = video.slug
        } else {
          lienVideo = "https://www.youtube.com/embed/" + video.slug
        }
        this.videos.push({
          titre: video.titre,
          slug: video.slug,
          auteur: video.auteur,
          lienAuteur: video.lienAuteur,
          lienVideo: lienVideo
        })
      }
    }
  }

  MAJLienExercices (objectif: Objectif) {
    this.lienExercices = environment.urlMathALEA
    let nbExercices = 0
    for (const exercice of objectif.exercices) {
      if (exercice.slug !== '' && exercice.slug.slice(0, 4) !== 'http') {
        this.lienExercices = this.lienExercices.concat('ex=', exercice.slug, ',i=0&')
        nbExercices ++
      }
    }
    this.lienExercices = this.lienExercices.concat('v=e&z=1.5')
    if (nbExercices === 0) this.lienExercices = ''
  }

  MAJExercices (objectif: Objectif) {
    this.exercices = []
    for (const exercice of objectif.exercices) {
      if (exercice.slug !== '') {
        this.exercices.push({
          id: exercice.id,
          slug: exercice.slug,
          lien: `${environment.urlMathALEA}ex=${exercice.slug},i=0&serie=&v=e&z=1.5`,
          isInteractif: exercice.isInteractif,
          description: exercice.description
        })
        this.exercices[this.exercices.length - 1].lien = this.exercices[this.exercices.length - 1].lien.replace(/&ex=/g, ',i=0&ex=') // dans le cas où il y aurait plusieurs exercices dans le même slug
        if (this.outilsService.estMathsMentales(exercice.slug)) {
          this.exercices[this.exercices.length - 1].lien = exercice.slug + '&embed=' + environment.origine
        } else if (exercice.slug.slice(0, 4) === 'http') {
          this.exercices[this.exercices.length - 1].lien = exercice.slug
        }
        if (this.estPresentDansLePanier(exercice.id)) {
          this.exercices[this.exercices.length - 1].estDansLePanier = true
        } else {
          this.exercices[this.exercices.length - 1].estDansLePanier = false
        }
      }
    }
    this.verifierSiTousLesExercicesSontPresentsDansLePanier()
  }

  MAJLienTelechargement (reference: string, type: string) {
    const lien = `assets/${type}/${reference.slice(0, 1)}e/${type.charAt(0).toUpperCase() + type.slice(1)}_${reference}.pdf`
    const xhttp = new XMLHttpRequest()
    xhttp.onreadystatechange = function () {
      if (this.readyState === 4 && this.status === 200) {
        majDivLigneTelechargement(type, lien)
      }
    }
    xhttp.open("HEAD", lien, true)
    xhttp.send()

    function majDivLigneTelechargement (type: string, lien: string) {
      let divId = '', description
      switch (type) {
        case 'entrainement':
          divId = 'lienEntrainement'
          description = 'la feuille d\'entraînement'
          break
        case 'test':
          divId = 'lienTest'
          description = 'les tests'
          break
      }
      const div = document.getElementById(divId)
      if (div !== null) {
        div.innerHTML = `<a href=${lien}>
        Télécharger ${description}
          &nbsp;
          <i class='image is-24x24 is-inline-block'>
            <img src='/assets/img/cc0/pdf-file-format-symbol-svgrepo-com.svg' />
          </i>
        </a>`
        div.style.display = 'block'
      }
      const divTelechargement = document.getElementById('divTelechargements')
      if (divTelechargement !== null) {
        divTelechargement.classList.remove('cache')
      }
    }
  }

  MAJAffichageSequences () {
    const divSequences = document.getElementById('divSequences')
    if (divSequences !== null && this.sequences.length === 0) divSequences.classList.add('cache')
  }

  ouvrirModaleExercices (lien: string | undefined) {
    if (typeof lien !== 'undefined') {
      this.infosModale = [[this.changerSerie(lien)], '', new Date() ]
    }
  }

  changerSerie (lien: string) {
    if (this.outilsService.estMathALEA(lien)) {
      const lienSplit = lien.split('&serie=')
      return lienSplit[0] + '&serie=' + Math.random().toString(16).slice(2, 6) + (lienSplit.length > 1 ? lienSplit[1] : '')
    } else {
      return lien
    }
  }

  toutAjouterAuPanier () {
    for (let i = 0; i < this.exercices.length; i++) {
      this.ajouterAuPanier(i)
    }
  }

  ajouterAuPanier (exerciceIndex: number) {
    const exercice = this.exercices[exerciceIndex]
    const description = exercice.description !== undefined && exercice.description !== '' ? exercice.description : this.exercices.length > 1 ? 'Exercices de niveau ' + (exerciceIndex + 1) : 'Lancer l\'exercice'
    const panierActuel = <PanierItem[]> this.storageService.get('panier')
    const panierItem = { exerciceId: exercice.id, objectif: this.titre, description, slug: exercice.slug }
    if (!this.estPresentDansLePanier(panierItem.exerciceId, panierActuel)) {
      this.exercices[exerciceIndex].estDansLePanier = true
      this.verifierSiTousLesExercicesSontPresentsDansLePanier()
      let panier = <PanierItem[]>[]
      if (panierActuel !== undefined) panier = panierActuel
      panier.push(panierItem)
      this.storageService.set('panier', panier)
    }
  }

  verifierSiTousLesExercicesSontPresentsDansLePanier () {
    if (this.tousLesExercicesSontPresentsDansLePanier()) {
      this.tousLesExercicesSontDansLePanier = true
    } else {
      this.tousLesExercicesSontDansLePanier = false
    }
  }

  tousLesExercicesSontPresentsDansLePanier () {
    for (const exercice of this.exercices) {
      if (!exercice.estDansLePanier) return false
    }
    return true
  }

  estPresentDansLePanier (exerciceId: number, panierActuel: PanierItem[] = <PanierItem[]> this.storageService.get('panier')) {
    if (panierActuel !== undefined) {
      for (const panierActuelItem of panierActuel) {
        if (panierActuelItem !== null && panierActuelItem.exerciceId === exerciceId) return true
      }
    }
    return false
  }

  scrollBack (): void {
    this.viewportScroller.scrollToAnchor('divExercices')
  }
}

<div class="container is-max-desktop centre">
  <h1 id="titre" [class]="'title is-2 is-' + niveau">{{ titre }}</h1>
  <div [class]="'is-' + niveau" *ngIf="rappelDuCoursHTML !== '' || rappelDuCoursImage !== '' || rappelDuCoursInstrumenpoche !== ''">
    <h2 [class]="'mb-5 pb-5 subtitle is-3 is-' + niveau">Rappel du cours</h2>
    <div class="has-text-centered pb-5">
      <p *ngIf="rappelDuCoursHTML !== ''" [mathjax]="rappelDuCoursHTML" class="is-size-5"></p>
      <img *ngIf="rappelDuCoursImage !== ''" [src]="rappelDuCoursImage" />
      <app-animation-instrumenpoche *ngIf="rappelDuCoursInstrumenpoche !== ''" [nomAnimation]="rappelDuCoursInstrumenpoche" class="centre"></app-animation-instrumenpoche>
    </div>
  </div>
  <div [class]="'is-' + niveau" *ngIf="videos.length > 0">
    <h2 [class]="'subtitle is-3 is-' + niveau">Vidéo{{videos.length > 1 ? 's' : ''}} d'explication</h2>
    <div class='pb-5' *ngFor="let video of videos">
      <h3 *ngIf="video.titre !== ''" [class]="'subtitle is-4 is-' + niveau">{{video.titre}}</h3>
      <div class="image is-16by9"><iframe class="has-ratio" [src]="video.lienVideo| safe" allowfullscreen></iframe></div>
      <p><u>Vidéo de <a [href]="video.lienAuteur" target="_blank" rel="noopener noreferrer">{{ video.auteur }}</a></u></p>
    </div>
  </div>
  <div id="divExercices" *ngIf="exercices.length > 0" [class]="'is-' + niveau">
    <h2 [class]="'subtitle is-3 is-' + niveau">
      <a (click)="ouvrirModaleExercices(lienExercices)">
        S'entraîner
        &nbsp;
        <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/fullscreen-svgrepo-com.svg'" [dropdown]="'Lancer les exercices'"></app-bouton-dropdown-simple>
      </a>
      <span *ngIf="storageService.modeEnseignant">
        &nbsp;
        <app-bouton-imprimer [lien]="lienExercices"></app-bouton-imprimer>
        &nbsp;
        <a *ngIf="!tousLesExercicesSontDansLePanier" (click)="toutAjouterAuPanier()">
          <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/cart-plus-svgrepo-com.svg'" [dropdown]="'Ajouter tous les exercices au panier'"></app-bouton-dropdown-simple>
        </a>
        <a *ngIf="tousLesExercicesSontDansLePanier">
          <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/cart-check-svgrepo-com.svg'" [dropdown]="'Les exercices sont tous déjà dans le panier'"></app-bouton-dropdown-simple>
        </a>
      </span>
    </h2>
    <div><br></div>
    <div *ngFor="let exercice of exercices; index as i">
      <h3 class="title is-4 is-inline-block">
        <a (click)="ouvrirModaleExercices(exercice.lien)">
          {{ exercice.description !== undefined && exercice.description !== '' ? exercice.description : exercices.length > 1 ? 'Exercices de niveau ' + (i + 1) : 'Lancer l\'exercice' }}
          &nbsp;
          <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/fullscreen-svgrepo-com.svg'" [dropdown]="'Lancer l\'exercice'"></app-bouton-dropdown-simple>
        </a>
        <span *ngIf="storageService.modeEnseignant">
          &nbsp;
          <app-bouton-imprimer [lien]="exercice.lien"></app-bouton-imprimer>
          &nbsp;
          <a *ngIf="!exercice.estDansLePanier" (click)="ajouterAuPanier(i)">
            <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/cart-plus-svgrepo-com.svg'" [dropdown]="'Ajouter l\'exercice au panier'"></app-bouton-dropdown-simple>
          </a>
          <span *ngIf="exercice.estDansLePanier">
            <app-bouton-dropdown-simple [bouton]="'/assets/img/cc0/cart-check-svgrepo-com.svg'" [dropdown]="'L\'exercice est déjà présent dans le panier'"></app-bouton-dropdown-simple>
          </span>
        </span>
      </h3>
      <div><br></div>
    </div>
  </div>
  <div id="divTelechargements" [class]="'pb-5 is-' + niveau">
    <h2 [class]="'subtitle is-3 is-' + niveau">Téléchargements</h2>
    <div class="p-1">
      <div id="lienEntrainement" class="p-1 cache"></div>
      <div id="lienTest" class="p-1 cache"></div>
    </div>
  </div>
  <div id="liens" [class]="'is-fin is-' + niveau">
    <h2 [class]="'subtitle is-3 is-' + niveau">Séquence{{ sequences.length > 1 ? 's' : '' }}</h2>
    <div><br></div>
    <p>Cet objectif fait partie de :</p>
    <br>
    <ul>
      <li class="title is-4" *ngFor="let sequence of sequences">
        <a [ngStyle]="{'color' : 'var(--base' + sequence.reference.slice(1, 2) + 'e)'}" [routerLink]="['/sequence/' + sequence.reference]">
          {{'Séquence ' + sequence.reference.slice(3) + ' : ' + sequence.titre }}
        </a>
      </li>
    </ul>
    <div><br><br></div>
  </div>
</div>
<app-modale-exercices [infosModale]="infosModale" (modaleFermee)="scrollBack()"></app-modale-exercices>

// src/topmaths/components/Objectif.svelte
<script lang="ts">
  import {
    modeEnseignant,
    modePerso,
    niveauxObjectifs,
    niveauxSequences,
    reference
  } from '../services/store'
  import type { ObjectifObjectif } from '../services/types'
  import { getTitre, goVue } from '../services/outils'
  import { afterUpdate, onMount, onDestroy, tick } from 'svelte'
  import type { Unsubscriber } from 'svelte/store'
  import {
    mathaleaRenderDiv
  } from '../../lib/mathalea'
  import {
    estPresentDansLePanier,
    tousLesExercicesSontPresentsDansLePanier
  } from '../services/panier'
  import iepLoadPromise from 'instrumenpoche'
  import BoutonsExercices from './mini-components/BoutonsExercices.svelte'

  onMount(() => {
    window.scrollTo({
      top: 0
    })
  })

  export let title = 'topmaths.fr - Séquence'
  let objectif = {} as ObjectifObjectif
  let tousLesExercicesSontDansLePanier = false
  let niveau = '' as string
  let exercicesDeBrevetDansLePanier = false
  let nomsPanier: string[] = []
  let referenceObjectifUnsubscribe: Unsubscriber
  let niveauxObjectifsUnsubscribe: Unsubscriber
  surveillerChangementsDeReference()
  surveillerLeChargementDesDonnees()

  afterUpdate(async () => {
    if (objectif.rappelDuCoursHTML !== '') {
      await tick()
      const rappelDuCoursHTML = document.getElementById('rappelDuCoursHTML')
      if (rappelDuCoursHTML !== null) mathaleaRenderDiv(rappelDuCoursHTML)
    }
    if (objectif.rappelDuCoursInstrumenpoche !== undefined && objectif.rappelDuCoursInstrumenpoche !== '') loadIep()
  })

  function surveillerChangementsDeReference () {
    referenceObjectifUnsubscribe = reference.subscribe(() => MAJPage())
    onDestroy(referenceObjectifUnsubscribe)
  }

  function surveillerLeChargementDesDonnees () {
    niveauxObjectifsUnsubscribe = niveauxObjectifs.subscribe(() => MAJPage())
    onDestroy(niveauxObjectifsUnsubscribe)
  }

  function lesDonneesSontChargees () {
    return $niveauxObjectifs.length > 0 && $niveauxSequences.length > 0
  }

  function MAJPage () {
    if (lesDonneesSontChargees() && $reference.slice(0, 1) !== 'S') {
      objectif = getObjectif()
      niveau = objectif.reference.slice(0, 1) + 'e'
      MAJProprietes()
    }
  }

  function getObjectif () {
    for (const niveau of $niveauxObjectifs) {
      for (const theme of niveau.themes) {
        for (const sousTheme of theme.sousThemes) {
          for (const objectif of sousTheme.objectifs) {
            if (objectif.reference === $reference) {
              return objectif
            }
          }
        }
      }
    }
    return {} as ObjectifObjectif
  }

  function MAJProprietes () {
    title = objectif.reference + ' : ' + getTitre(objectif)
    MakeNomsPanier()
    MAJPanier()
  }

  function MakeNomsPanier () {
    nomsPanier = []
    for (let i = 0; i < objectif.exercices.length; i++) {
      nomsPanier.push(objectif.reference + ' ' + getTitre(objectif))
    }
  }

  function MAJPanier () {
    for (const exercice of objectif.exercices) {
      if (exercice.slug !== '') {
        exercice.estDansLePanier = estPresentDansLePanier(exercice.id)
      }
    }
    tousLesExercicesSontDansLePanier =
      tousLesExercicesSontPresentsDansLePanier(objectif)
    if (objectif.exercicesDeBrevet !== undefined) {
      for (const exercice of objectif.exercicesDeBrevet) {
        if (exercice.slug !== '') {
          exercice.estDansLePanier = estPresentDansLePanier(exercice.id)
        }
      }
      exercicesDeBrevetDansLePanier = tousLesExercicesSontPresentsDansLePanier(
        objectif,
        true
      )
    }
  }

  function loadIep () {
    const url = `topmaths/data/instrumenpoche/${objectif.rappelDuCoursInstrumenpoche}.xml`
    fetch(url)
      .then(response => response.text())
      .then(xml => {
        const container = document.getElementById('divIEP')
        iepLoadPromise(container, xml).then(iepApp => {
        }).catch(error => {
          console.log(error)
        })
      })
      .catch(err => {
        console.error(err)
      })
  }
</script>

<svelte:head>
  <title>{title}</title>
</svelte:head>

<div class="container is-max-desktop centre">
  <h1 id="titre" class="title is-2 mb-0 is-{niveau}">
    {objectif.reference + ' : ' + getTitre(objectif)}
  </h1>
  {#if objectif.rappelDuCoursHTML !== '' || objectif.rappelDuCoursImage !== '' || (objectif.rappelDuCoursInstrumenpoche !== undefined && objectif.rappelDuCoursInstrumenpoche !== '')}
    <div class="is-{niveau}">
      <h2 class="mb-5 pb-5 subtitle is-3 is-{niveau}">Rappel du cours</h2>
      <div class="has-text-centered pb-5">
        {#if objectif.rappelDuCoursHTML !== ''}
          <p
            id="rappelDuCoursHTML"
            class="is-size-5 question"
            contenteditable="false"
            bind:innerHTML={objectif.rappelDuCoursHTML}
          />
        {/if}
        <br />
        {#if objectif.rappelDuCoursImage !== ''}
          <img class="is-inline-block" src={objectif.rappelDuCoursImage} />
        {/if}
        {#if objectif.rappelDuCoursInstrumenpoche !== undefined && objectif.rappelDuCoursInstrumenpoche !== ''}
        <div style="text-align: center;">
          <div class="is-inline-block" id="divIEP"></div>
        </div>
        {/if}
      </div>
    </div>
  {/if}
  {#if objectif.videos.length > 0}
    <div class="is-{niveau}">
      <h2 class="subtitle is-3 mb-0 is-{niveau}">
        Vidéo{objectif.videos.length > 1 ? 's' : ''} d'explication
      </h2>
      {#each objectif.videos as video}
        <div class="pb-5">
          {#if video.titre !== ''}
            <h3 class="subtitle is-4 mb-0 is-{niveau}">{video.titre}</h3>
          {/if}
          <div class="image is-16by9">
            <iframe
              class="has-ratio"
              src={video.slug}
              title="Vidéo d'explication"
              allowfullscreen
            />
          </div>
          Vidéo de&nbsp;<a
            href={video.lienAuteur}
            target="_blank"
            rel="noopener noreferrer"
          >
            <button>
              {video.auteur}
            </button>
          </a>
        </div>
      {/each}
    </div>
  {/if}
  {#if objectif.exercices.length > 0}
    <div
      id="divExercices"
      class="is-{niveau}"
      class:is-fin = {objectif.sequences.length === 0 &&
        !objectif.telechargementsDisponibles.entrainement &&
        !objectif.telechargementsDisponibles.test}
    >
      <h2 class="subtitle is-3 is-{niveau}">
        <BoutonsExercices
          reference = {objectif.reference}
          exercices = {objectif.exercices}
          videos = {objectif.videos}
          lienExercices = {objectif.lienExercices}
          panierRempli = {tousLesExercicesSontDansLePanier}
          titre = {'S\'entraîner'}
          nomsPanier = {nomsPanier}
        />
      </h2>
      <div class="p-3">
        {#each objectif.exercices as exercice, i}
          <div>
            <h3 class="is-size-4 mb-0 is-inline-block">
              <BoutonsExercices
                reference = {objectif.reference}
                exercices = {[objectif.exercices[i]]}
                videos = {objectif.videos}
                lienExercices = {exercice.lien}
                panierRempli = {exercice.estDansLePanier}
                titre = {exercice.description !== ''
                  ? exercice.description
                  : objectif.exercices.length > 1
                    ? 'Exercices de niveau ' + (i + 1)
                    : "Lancer l'exercice"}
                indiceExercice = {i}
                nomsPanier = {[objectif.reference + ' ' + getTitre(objectif)]}
              />
            </h3>
            <div><br /></div>
          </div>
        {/each}
      </div>
    </div>
  {/if}
  {#if objectif.lienExercicesDeBrevet !== ''}
    <div class="pb-5 is-{niveau}">
      <h2 class="subtitle is-3 is-{niveau}">En route vers le brevet</h2>
      <div class="p-1">
        Tu ne peux pas encore faire ces exercices en entier, mais avec ce que tu
        viens d'apprendre, tu sais répondre à au moins une question de chacun
        d'entre eux !
      </div>
      <h3 class="is-size-4 mb-0 is-inline-block">
        <BoutonsExercices
          exercices = {objectif.exercicesDeBrevet}
          videos = {objectif.videos}
          lienExercices = {objectif.lienExercicesDeBrevet}
          panierRempli = {exercicesDeBrevetDansLePanier}
          titre = {'Lancer les exercices de brevet'}
          exercicesDeBrevet = {true}
          nomsPanier = {[objectif.reference + ' ' + getTitre(objectif) + ' Brevet ']}
        />
      </h3>
    </div>
  {/if}
  {#if objectif.telechargementsDisponibles.entrainement || objectif.telechargementsDisponibles.test || ($modePerso && objectif.telechargementsDisponibles.fiche)}
    <div
      class="{objectif.sequences.length === 0 ? 'is-fin ' : ''}pb-5 is-{niveau}"
    >
      <h2 class="subtitle is-3 is-{niveau}">Téléchargements</h2>
      <div class="p-1">
        {#if objectif.telechargementsDisponibles.entrainement}
          <div class="p-1">
            <a
              href="topmaths/entrainement/{niveau}/Entrainement_{$reference}.pdf"
            >
              <button>
                Télécharger la feuille d'entraînement &nbsp;
                <i class="image is-24x24 is-inline-block">
                  <img
                    src="/topmaths/img/cc0/pdf-file-format-symbol-svgrepo-com.svg"
                    alt="Fichier PDF"
                  />
                </i>
              </button>
            </a>
          </div>
        {/if}
        {#if $modeEnseignant && objectif.telechargementsDisponibles.test}
          <div class="p-1">
            <a href="topmaths/test/{niveau}/Test_{$reference}.pdf">
              <button>
                Télécharger les tests &nbsp;
                <i class="image is-24x24 is-inline-block">
                  <img
                    src="/topmaths/img/cc0/pdf-file-format-symbol-svgrepo-com.svg"
                    alt="Fichier PDF"
                  />
                </i>
              </button>
            </a>
          </div>
        {/if}
        {#if $modePerso && objectif.telechargementsDisponibles.fiche}
          {#each objectif.telechargementsDisponibles.niveauxFiches as niveauDisponible}
            {#each objectif.fiches as fiche}
              {#if fiche.niveaux.length === 0 || fiche.niveaux.includes(niveauDisponible)}
                <div class="p-1">
                  <a href="topmaths/fiches/objectifs/{objectif.niveau}/{niveauDisponible}_{fiche.reference.split('-')[1] === undefined ? (fiche.reference + '_Fiche') : fiche.reference.split('-')[0] + '_Fiche-' + fiche.reference.split('-')[1]}.pdf">
                    <button>
                      Télécharger la fiche{fiche.reference.split('-')[1] === undefined ? '' : ' ' + fiche.reference.split('-')[1]}{objectif.telechargementsDisponibles.niveauxFiches.length > 1 ? ` (${niveauDisponible})` : ''} &nbsp;
                      <i class="image is-24x24 is-inline-block">
                        <img
                          src="/topmaths/img/cc0/pdf-file-format-symbol-svgrepo-com.svg"
                          alt="Fichier PDF"
                        />
                      </i>
                    </button>
                  </a>
                </div>
              {/if}
            {/each}
          {/each}
        {/if}
      </div>
    </div>
  {/if}
  {#if objectif.sequences.length > 0}
    <div class="is-fin is-{niveau}">
      <h2 class="subtitle is-3 is-{niveau}">
        Séquence{objectif.sequences.length > 1 ? 's' : ''}
      </h2>
      <p>Cet objectif fait partie de :</p>
      <br />
      <ul>
        {#each objectif.sequences as sequence}
          <li class="title is-4">
            <a
              href="/?v=sequence&ref={sequence.reference}"
              style="color: var(--base{sequence.reference.slice(1, 2)}e);"
              on:click={(event) =>
                goVue(event, 'sequence', sequence.reference)}
            >
              {'Séquence ' +
                sequence.reference.slice(3) +
                ' : ' +
                sequence.titre}
            </a>
          </li>
        {/each}
      </ul>
      <div><br /><br /></div>
    </div>
  {/if}
</div>
