// src/app/objectifs/objectifs.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core'
import { Router, ActivatedRoute, NavigationStart, Event as NavigationEvent } from '@angular/router'
import { Subscription } from 'rxjs'
import { DataService } from '../services/data.service'

interface Ligne {
  niveau?: string;
  theme?: string;
  sousTheme?: string;
  reference?: string;
  titre?: string
}
@Component({
  selector: 'app-objectifs',
  templateUrl: './objectifs.component.html',
  styleUrls: []
})
export class ObjectifsComponent implements OnInit, OnDestroy {
  lignes: Ligne[]
  filtre: Ligne
  ongletActif: string
  navigationEventSubscription: Subscription

  // eslint-disable-next-line no-unused-vars
  constructor(private dataService: DataService, private activatedRoute: ActivatedRoute, private router: Router) {
    this.lignes = []
    this.filtre = {}
    this.ongletActif = 'tout'
    this.navigationEventSubscription = new Subscription
    this.MAJOngletActif()
  }

  ngOnInit(): void {
    this.MAJFiltre()
    this.MAJLignes()
  }

  ngOnDestroy() {
    this.navigationEventSubscription.unsubscribe()
  }

  MAJOngletActif() {
    this.navigationEventSubscription = this.router.events.subscribe((event: NavigationEvent) => {
      if (event instanceof NavigationStart) {
        this.ongletActif = event.url.split('/')[2]
      }
    })
  }

  MAJFiltre() {
    this.activatedRoute.params.subscribe(params => {
      this.filtre.niveau = params.niveau
      this.filtre.theme = params.theme
      this.filtre.sousTheme = params.sousTheme
    })
  }

  MAJLignes() {
    this.lignes = []
    for (const niveau of this.dataService.niveauxObjectifs) {
      this.lignes.push({ niveau: niveau.nom })
      for (const theme of niveau.themes) {
        this.lignes.push({ niveau: niveau.nom, theme: theme.nom })
        for (const sousTheme of theme.sousThemes) {
          this.lignes.push({ niveau: niveau.nom, theme: theme.nom, sousTheme: sousTheme.nom })
          for (const objectif of sousTheme.objectifs) {
            this.lignes.push({ niveau: niveau.nom, theme: theme.nom, sousTheme: sousTheme.nom, reference: objectif.reference, titre: objectif.titre })
          }
        }
      }
      this.lignes.push({ niveau: 'fin' })
    }
  }
}

<div class="container is-max-desktop centre">
  <div class="tabs is-medium is-centered">
    <ul class="tabs-menu is-rounded">
      <li><a [ngClass]="{'subtitle is-4 is-tout is-left-side': true, 'is-active': ongletActif === 'tout'}" [routerLink]="['/objectifs/tout']">Tout</a></li>
      <li *ngFor="let ligne of lignes;">
        <a *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.theme === undefined" [routerLink]="['/objectifs', ligne.niveau]" [ngClass]="{'is-active': ongletActif === ligne.niveau, 'subtitle is-4': true, 'is-6e': ligne.niveau === '6e', 'is-5e': ligne.niveau === '5e', 'is-4e': ligne.niveau === '4e', 'is-3e is-right-side': ligne.niveau === '3e'}">{{ligne.niveau}}</a>
      </li>
    </ul>
  </div>
  <div>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== null && filtre.periode !== undefined && filtre.periode > 0}" (click)="filtre.periode = 0">Période</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 1}" (click)="filtre.periode === 1 ? filtre.periode = 0 : filtre.periode = 1">1</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 2}" (click)="filtre.periode === 2 ? filtre.periode = 0 : filtre.periode = 2">2</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 3}" (click)="filtre.periode === 3 ? filtre.periode = 0 : filtre.periode = 3">3</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 4}" (click)="filtre.periode === 4 ? filtre.periode = 0 : filtre.periode = 4">4</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 5}" (click)="filtre.periode === 5 ? filtre.periode = 0 : filtre.periode = 5">5</button>
  </div>
  <input style="text-align:center; font-size:x-large ;" type="email" class="form-control" id="search-text" aria-describedby="search-text" [(ngModel)]="texteRecherche" placeholder="Recherche" autofocus>
  <div><br></div>
  <div class="container is-max-desktop centre">
    <span *ngFor="let ligne of lignes | objectifsFilter: texteRecherche; index as i;">
      <div *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.theme === undefined && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && i > 0 && (lignes[i].niveau !== lignes[i + 1].niveau || filtre.niveau === 'tout')"><br></div>
      <h1 *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.theme === undefined && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)" [class]="'title is-2 p-2 is-' + ligne.niveau">{{ligne.niveau}}</h1>
      <h2 *ngIf="ligne.theme !== undefined && ligne.niveau !== 'fin' && ligne.sousTheme === undefined && filtre.periode !== undefined && (filtre.periode === 0 || ligne.theme.nbObjectifsParPeriode[filtre.periode - 1] > 0) && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.theme === undefined || filtre.theme.nom === ligne.theme.nom)" [class]="'subtitle is-3 pt-2 is-' + ligne.niveau">{{ligne.theme.nom}}</h2>
      <h3 *ngIf="ligne.sousTheme !== undefined && ligne.sousTheme !== '' && ligne.niveau !== 'fin' && ligne.reference === undefined && filtre.periode !== undefined && (filtre.periode === 0 || ligne.sousTheme.nbObjectifsParPeriode[filtre.periode - 1] > 0) && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.theme === undefined || filtre.theme.nom === ligne.theme.nom) && (filtre.sousTheme === undefined || filtre.sousTheme === ligne.sousTheme.nom)" [class]="'subtitle is-4 p-4 is-' + ligne.niveau">{{ligne.sousTheme.nom}}</h3>
      <a routerLink="/objectif/{{ligne.reference}}" routerLinkActive="active" *ngIf="ligne.reference !== undefined && ligne.niveau !== 'fin' && filtre.periode !== null && (ligne.periode === filtre.periode || filtre.periode === undefined || filtre.periode === 0) && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.theme === undefined || filtre.theme.nom === ligne.theme.nom) && (filtre.sousTheme === undefined || filtre.sousTheme === ligne.sousTheme)">
        <p [ngClass]="{'p-1 is-size-5': true, 'is-fin': lignes[i].niveau !== lignes[i + 1].niveau, 'is-6e': ligne.niveau === '6e', 'is-5e': ligne.niveau === '5e', 'is-4e': ligne.niveau === '4e', 'is-3e': ligne.niveau === '3e'}">
          {{ligne.reference}} : {{ligne.titre}}<br>
        </p>
      </a>
    </span>
  </div>
</div>

// src/topmaths/components/Objectifs.svelte
<script lang="ts">
  import { modeEnseignant, niveauxObjectifs, titresProchesDesAttendus } from '../services/store'
  import { goVue, normaliser } from '../services/outils'
  import { onDestroy } from 'svelte'
  import type { Unsubscriber } from 'svelte/store'
  import { writable, derived } from 'svelte/store'
  import type { LigneObjectif } from '../services/types'

  const filtre = {
    niveau: 'tout',
    periode: 0,
    theme: { nom: '', nbObjectifsParPeriode: [] },
    sousTheme: { nom: '', nbObjectifsParPeriode: [] },
    reference: '',
    titre: '',
    titreSimplifie: ''
  } as LigneObjectif
  const texteRecherche = writable('')
  const lignes = writable<LigneObjectif[]>([])
  const lignesFiltrees = derived(
    [texteRecherche, lignes],
    ([$texteRecherche, $lignes]) => getLignesFiltrees($texteRecherche, $lignes)
  )

  let niveauxObjectifsUnsubscribe: Unsubscriber

  updateParamsFromUrl()
  MAJPage()
  surveillerLeChargementDesDonnees()
  addEventListener('popstate', updateParamsFromUrl)
  onDestroy(() => {
    removeEventListener('popstate', updateParamsFromUrl)
  })

  function updateParamsFromUrl () {
    const url = new URL(window.location.href)
    const entries = url.searchParams.entries()
    for (const entry of entries) {
      if (entry[0] === 'niveau') filtre.niveau = entry[1]
      if (entry[0] === 'periode') filtre.periode = Number(entry[1])
    }
  }

  function surveillerLeChargementDesDonnees () {
    niveauxObjectifsUnsubscribe = niveauxObjectifs.subscribe(() => MAJPage())
    onDestroy(niveauxObjectifsUnsubscribe)
  }

  function MAJPage () {
    if (lesDonneesSontChargees()) {
      MAJLignes()
    }
  }

  function lesDonneesSontChargees () {
    return $niveauxObjectifs.length > 0
  }

  function MAJLignes () {
    const lignesTemp = []
    for (const niveau of $niveauxObjectifs) {
      lignesTemp.push({
        niveau: niveau.nom,
        periode: 0,
        theme: { nom: '', nbObjectifsParPeriode: [] },
        sousTheme: { nom: '', nbObjectifsParPeriode: [] },
        reference: '',
        titre: '',
        titreSimplifie: ''
      })
      for (const theme of niveau.themes) {
        lignesTemp.push({
          niveau: niveau.nom,
          periode: 0,
          theme: {
            nom: theme.nom,
            nbObjectifsParPeriode: theme.nbObjectifsParPeriode
          },
          sousTheme: { nom: '', nbObjectifsParPeriode: [] },
          reference: '',
          titre: '',
          titreSimplifie: ''
        })
        for (const sousTheme of theme.sousThemes) {
          lignesTemp.push({
            niveau: niveau.nom,
            periode: 0,
            theme: {
              nom: theme.nom,
              nbObjectifsParPeriode: theme.nbObjectifsParPeriode
            },
            sousTheme: {
              nom: sousTheme.nom,
              nbObjectifsParPeriode: sousTheme.nbObjectifsParPeriode
            },
            reference: '',
            titre: '',
            titreSimplifie: ''
          })
          for (const objectif of sousTheme.objectifs) {
            lignesTemp.push({
              niveau: niveau.nom,
              periode: objectif.periode,
              theme: {
                nom: theme.nom,
                nbObjectifsParPeriode: theme.nbObjectifsParPeriode
              },
              sousTheme: {
                nom: sousTheme.nom,
                nbObjectifsParPeriode: sousTheme.nbObjectifsParPeriode
              },
              reference: objectif.reference,
              titre: objectif.titre,
              titreSimplifie: objectif.titreSimplifie
            })
          }
        }
      }
      lignesTemp.push({
        niveau: 'fin',
        periode: 0,
        theme: { nom: '', nbObjectifsParPeriode: [] },
        sousTheme: { nom: '', nbObjectifsParPeriode: [] },
        reference: '',
        titre: '',
        titreSimplifie: ''
      })
    }
    lignes.set(lignesTemp)
  }

  function getLignesFiltrees (texteRecherche: string, lignes: LigneObjectif[]): LigneObjectif[] {
    if (texteRecherche === '') return lignes
    const motsCherches = normaliser(texteRecherche).split(' ')
    return lignes.filter((ligne) => {
      for (const mot of motsCherches) {
        if (!motTrouve(mot, ligne)) return false
      }
      return true
    })
  }

  function motTrouve (mot: string, ligne: LigneObjectif) {
    if (
      ligne.niveau !== undefined &&
      normaliser(ligne.niveau).includes(mot)
    ) { return true }
    if (
      ligne.reference !== undefined &&
      normaliser(ligne.reference).includes(mot)
    ) { return true }
    if (
      ligne.titre !== undefined &&
      normaliser(ligne.titre).includes(mot)
    ) { return true }
    if (
      ligne.titreSimplifie !== undefined &&
      normaliser(ligne.titreSimplifie).includes(mot)
    ) { return true }
    return false
  }

  function clicFiltre (niveau: string, periode?: number) {
    if (niveau !== '') {
      filtre.niveau = niveau
    }
    if (periode !== undefined) {
      filtre.periode === periode
        ? (filtre.periode = 0)
        : (filtre.periode = periode)
    }
    window.history.pushState({}, '', `?v=objectifs&niveau=${filtre.niveau}&periode=${filtre.periode}`)
  }
</script>

<svelte:head>
  <title>Liste des objectifs topmaths</title>
</svelte:head>

<div class="w-screen max-w-screen-lg">
  <div class="tabs is-medium is-centered">
    <ul class="tabs-menu is-full-rounded" style="border: none">
      <li>
        <button
          class="subtitle is-4 px-5 is-tout is-left-side"
          class:is-active={filtre.niveau === 'tout'}
          on:click={() => clicFiltre('tout')}>Tout</button
        >
      </li>
      {#each $lignes as ligne}
        <li>
          {#if ligne.niveau !== '' && ligne.niveau !== 'fin' && ligne.theme.nom === ''}
            <button
              on:click={() => clicFiltre(ligne.niveau ?? '')}
              class:is-active={filtre.niveau === ligne.niveau}
              class="subtitle is-4 px-5 is-{ligne.niveau}"
              class:is-right-side={ligne.niveau === '3e'}>{ligne.niveau}</button
            >
          {/if}
        </li>
      {/each}
    </ul>
  </div>
  <div class="is-flex is-justify-content-center pt-2 pb-1" style="overflow:auto">
    <span
      ><button
        class="button is-rounded is-link mb-5 mx-1 is-medium"
        class:is-light={filtre.periode !== null &&
          filtre.periode !== undefined &&
          filtre.periode > 0}
        on:click={() => clicFiltre('', 0)}>Période</button
      ></span
    >
    {#each [1, 2, 3, 4, 5] as periode}
      <span>
        <button
          class="button is-rounded is-link mb-5 mx-1 is-medium"
          class:is-light={filtre.periode !== periode}
          on:click={() => clicFiltre('', periode)}>{periode}</button
        >
      </span>
    {/each}
  </div>
  <input
    class="p-1"
    style="text-align:center; font-size:x-large;"
    type="text"
    aria-describedby="Champ pour rechercher un objectif"
    autocomplete="off"
    placeholder="Recherche"
    bind:value={$texteRecherche}
    on:input
  />
  {#if $modeEnseignant}
  <label class="absolute mt-2 ml-2">
    <input class="translate-y-1" type="checkbox" bind:checked={$titresProchesDesAttendus} />
      Intitulés proches des attendus de fin d'année
  </label>
  {/if}
  <div><br /></div>
  <div>
    {#each $lignesFiltrees as ligne, i}
      {#if ligne.theme.nom !== 'Extra'}
        <span>
          {#if ligne.niveau !== '' && ligne.niveau !== 'fin' && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && ligne.theme.nom === '' && ligne.sousTheme.nom === '' && ligne.reference === ''}
            <h1 class="title is-2 p-2 is-{ligne.niveau}">
              {ligne.niveau}
            </h1>
          {/if}
          {#if ligne.niveau !== 'fin' && (filtre.periode === 0 || ligne.theme.nbObjectifsParPeriode[filtre.periode - 1] > 0) && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.theme.nom === '' || filtre.theme.nom === ligne.theme.nom) && ligne.theme.nom !== '' && ligne.sousTheme.nom === '' && ligne.reference === ''}
            <h2 class="subtitle is-3 pt-2 is-{ligne.niveau}">
              {ligne.theme.nom}
            </h2>
          {/if}
          {#if ligne.niveau !== 'fin' && (filtre.periode === 0 || ligne.sousTheme.nbObjectifsParPeriode[filtre.periode - 1] > 0) && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.sousTheme.nom === '' || filtre.sousTheme.nom === ligne.sousTheme.nom) && ligne.sousTheme.nom !== '' && ligne.reference === ''}
            <h3 class="subtitle is-4 p-4 is-{ligne.niveau}">
              {ligne.sousTheme.nom}
            </h3>
          {/if}
          {#if ligne.niveau !== 'fin' && (filtre.periode === 0 || filtre.periode === ligne.periode) && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau) && (filtre.theme.nom === '' || filtre.theme.nom === ligne.theme.nom) && (filtre.sousTheme.nom === '' || filtre.sousTheme.nom === ligne.sousTheme.nom) && ligne.reference !== ''}
            <div
              class="p-1 is-size-5 is-{ligne.niveau}"
              class:is-fin={$texteRecherche === '' && ($lignesFiltrees[i + 1].niveau === 'fin' || $lignesFiltrees[i + 1].theme.nom === 'Extra')}
            >
              <a
                href="/?v=objectif&ref={ligne.reference}"
                on:click={(event) =>
                  goVue(event, 'objectif', ligne.reference ?? '')}
              >
                <div>
                  {ligne.reference} : {$titresProchesDesAttendus ||
                    ligne.titreSimplifie === undefined || ligne.titreSimplifie === ''
                    ? ligne.titre
                    : ligne.titreSimplifie}<br />
                </div>
              </a>
            </div>
          {/if}
        </span>
      {/if}
      {#if i > 0 && ligne.niveau === 'fin' && filtre.niveau === 'tout'}
        <div>
          <br />
        </div>
      {/if}
    {/each}
  </div>
</div>
