// src/app/sequences/sequences.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core'
import { Router, ActivatedRoute } from '@angular/router'
import { Subscription } from 'rxjs'
import { DataService } from '../services/data.service'

interface Ligne {
  niveau?: string,
  periode?: number,
  numero?: number,
  reference?: string,
  titre?: string
}
@Component({
  selector: 'app-sequences',
  templateUrl: './sequences.component.html',
  styleUrls: []
})
export class SequencesComponent implements OnInit, OnDestroy {
  lignesSequencesNormales: Ligne[]
  lignesSequencesParticulieres: Ligne[]
  filtre: Ligne
  texteRecherche: string
  navigationEventSubscription: Subscription
  dataMAJSubscription: Subscription
  ongletActif: string

  // eslint-disable-next-line no-unused-vars
  constructor (private dataService: DataService, private activatedRoute: ActivatedRoute, private router: Router) {
    this.lignesSequencesNormales = []
    this.lignesSequencesParticulieres = []
    this.filtre = {}
    this.texteRecherche = ''
    this.navigationEventSubscription = new Subscription
    this.dataMAJSubscription = new Subscription
    this.ongletActif = 'tout'
    this.MAJOngletActif()
    this.surveillerLeChargementDesDonnees()
  }

  ngOnInit (): void {
    if (this.lesDonneesSontChargees()) this.MAJPage()
  }

  ngOnDestroy () {
    this.navigationEventSubscription.unsubscribe()
    this.dataMAJSubscription.unsubscribe()
  }

  MAJOngletActif () {
    this.activatedRoute.params.subscribe(params => {
      this.ongletActif = params.niveau
      this.filtre.niveau = params.niveau
      if (params.periode !== undefined) this.filtre.periode = Number(params.periode)
    })
  }

  surveillerLeChargementDesDonnees () {
    this.dataMAJSubscription = this.dataService.dataMAJ.subscribe(valeurModifiee => {
      if (valeurModifiee === 'sequencesParticulieres' || valeurModifiee === 'niveauxSequences') {
        if (this.lesDonneesSontChargees()) this.MAJPage()
      }
    })
  }

  lesDonneesSontChargees () {
    return this.dataService.sequencesParticulieres.length > 0 && this.dataService.niveauxSequences.length > 0
  }

  MAJPage () {
    this.MAJLignesSequencesParticulieres()
    this.MAJLignesSequencesNormales()
  }

  MAJLignesSequencesParticulieres () {
    this.lignesSequencesParticulieres = []
    this.lignesSequencesParticulieres.push({ niveau: 'Séquences particulières' })
    for (const sequence of this.dataService.sequencesParticulieres) {
      this.lignesSequencesParticulieres.push({ niveau: 'Séquences particulières', reference: sequence.reference, titre: sequence.titre, numero: 0 })
    }
    this.lignesSequencesParticulieres.push({ niveau: 'fin' })
  }

  MAJLignesSequencesNormales () {
    this.lignesSequencesNormales = []
    for (const niveau of this.dataService.niveauxSequences) {
      this.lignesSequencesNormales.push({ niveau: niveau.nom })
      for (const sequence of niveau.sequences) {
        this.lignesSequencesNormales.push({ niveau: niveau.nom, reference: sequence.reference, titre: sequence.titre, periode: sequence.periode, numero: parseInt(sequence.reference.slice(3)) })
      }
      this.lignesSequencesNormales.push({ niveau: 'fin' })
    }
  }

  clicFiltre (niveau: string, periode?: number) {
    if (niveau !== '') {
      this.ongletActif = niveau
      this.filtre.niveau = niveau
    }
    if (periode !== undefined) {
      this.filtre.periode === periode ? this.filtre.periode = 0 : this.filtre.periode = periode
    }
    window.history.pushState('', '', `/#/sequences/${this.filtre.niveau}${this.filtre.periode ? '/' + this.filtre.periode : ''}`)
  }
}

<div class="container is-max-desktop centre">
  <!-- Menu -->
  <div class="tabs is-medium is-centered">
    <ul class="tabs-menu is-rounded">
      <li><a [ngClass]="{'subtitle is-4 is-tout is-left-side': true, 'is-active': ongletActif === 'tout'}" (click)="ongletActif = 'tout'; filtre.niveau = 'tout'">Tout</a></li>
      <li *ngFor="let ligne of lignesSequencesNormales;">
        <a *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.reference === undefined" (click)="ongletActif = ligne.niveau; filtre.niveau = ligne.niveau" [ngClass]="{'is-active': ongletActif === ligne.niveau, 'subtitle is-4': true, 'is-6e': ligne.niveau === '6e', 'is-5e': ligne.niveau === '5e', 'is-4e': ligne.niveau === '4e', 'is-3e is-right-side': ligne.niveau === '3e'}">{{ligne.niveau}}</a>
      </li>
    </ul>
  </div>
  <div class="is-flex is-justify-content-center" style="overflow:scroll">
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== null && filtre.periode !== undefined && filtre.periode > 0}" (click)="filtre.periode = 0">Période</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 1}" (click)="filtre.periode === 1 ? filtre.periode = 0 : filtre.periode = 1">1</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 2}" (click)="filtre.periode === 2 ? filtre.periode = 0 : filtre.periode = 2">2</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 3}" (click)="filtre.periode === 3 ? filtre.periode = 0 : filtre.periode = 3">3</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 4}" (click)="filtre.periode === 4 ? filtre.periode = 0 : filtre.periode = 4">4</button>
    <button [ngClass]="{'button is-rounded is-link mb-5 mx-1 is-medium': true, 'is-light': filtre.periode !== 5}" (click)="filtre.periode === 5 ? filtre.periode = 0 : filtre.periode = 5">5</button>
  </div>
  <input style="text-align:center; font-size:x-large ;" type="email" class="form-control" id="search-text" aria-describedby="search-text" [(ngModel)]="texteRecherche" placeholder="Recherche" autofocus>
  <div><br></div>
  <div class="container is-max-desktop centre">
    <!-- Séquences particulières -->
    <div>
      <a routerLink="/sequence/{{ligne.reference}}" routerLinkActive="active" *ngFor="let ligne of lignesSequencesParticulieres | sequencesFilter: texteRecherche; index as i">
        <h1 *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.reference === undefined" class="title is-3 p-2 is-tout">{{ligne.niveau}}</h1>
        <p *ngIf="ligne.reference !== undefined" [ngClass]="{'is-tout is-size-5': true, 'is-fin': lignesSequencesParticulieres[i].niveau !== lignesSequencesParticulieres[i + 1].niveau}">
          {{ligne.numero === 0 ? '' : 'Séquence ' + ligne.numero + ' : '}}{{ligne.titre}}<br>
        </p>
      </a>
    </div>
    <!-- Séquences normales -->
    <span *ngFor="let ligne of lignesSequencesNormales | sequencesFilter: texteRecherche; index as i">
      <div *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.reference === undefined && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)"><br></div>
      <h1 *ngIf="ligne.niveau !== undefined && ligne.niveau !== 'fin' && ligne.reference === undefined && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)" [class]="'title is-3 p-2 is-' + ligne.niveau">
        <span class="has-text-white">
          {{ligne.niveau}}
        </span>
      </h1>
      <a routerLink="/sequence/{{ligne.reference}}" routerLinkActive="active" *ngIf="ligne.reference !== undefined && ligne.niveau !== 'fin' && filtre.periode !== null && (ligne.periode === filtre.periode || filtre.periode === undefined || filtre.periode === 0) && (filtre.niveau === undefined || filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)">
        <p [ngClass]="{'p-1 is-size-5': true, 'is-fin': lignesSequencesNormales[i].niveau !== lignesSequencesNormales[i + 1].niveau, 'is-6e': ligne.niveau === '6e', 'is-5e': ligne.niveau === '5e', 'is-4e': ligne.niveau === '4e', 'is-3e': ligne.niveau === '3e'}">
          {{ligne.numero === 0 ? '' : 'Séquence ' + ligne.numero + ' : '}}{{ligne.titre}}
        </p>
      </a>
    </span>
  </div>
</div>

// src/topmaths/components/Sequences.svelte
<script lang="ts">
  import {
    niveauxSequences,
    sequencesParticulieres
  } from '../services/store'
  import { onDestroy } from 'svelte'
  import { outils } from '../services/outils'
  import type { Unsubscriber } from 'svelte/store'
  import { writable, derived } from 'svelte/store'

  interface Ligne {
    niveau: string
    periode: number
    numero: number
    reference: string
    titre: string
  }

  const filtre = {
    niveau: 'tout',
    periode: 0,
    numero: 0,
    reference: '',
    titre: ''
  } as Ligne
  const texteRecherche = writable<string>('')
  const lignesSequencesNormales = writable<Ligne[]>([])
  const lignesFiltreesSequencesNormales = derived(
    [texteRecherche, lignesSequencesNormales],
    ([$texteRecherche, $lignesSequencesNormales]) =>
      getLignesFiltrees($texteRecherche, $lignesSequencesNormales)
  )

  let niveauxSequencesUnsubscribe: Unsubscriber
  let sequencesParticulieresUnsubscribe: Unsubscriber
  let lignesSequencesParticulieres = [] as Ligne[]
  let ongletActif = 'tout'

  MAJPage()
  surveillerChargementDesDonnees()

  function lesDonneesSontChargees () {
    return $sequencesParticulieres.length > 0 && $niveauxSequences.length > 0
  }

  function MAJPage () {
    if (lesDonneesSontChargees()) {
      MAJLignesSequencesParticulieres()
      MAJLignesSequencesNormales()
    }
  }

  function MAJLignesSequencesParticulieres () {
    lignesSequencesParticulieres = []
    lignesSequencesParticulieres.push({
      niveau: 'Séquences particulières',
      periode: 0,
      numero: 0,
      reference: '',
      titre: ''
    })
    for (const sequence of $sequencesParticulieres) {
      lignesSequencesParticulieres.push({
        niveau: 'Séquences particulières',
        reference: sequence.reference,
        titre: sequence.titre,
        numero: 0,
        periode: 1
      })
    }
    lignesSequencesParticulieres.push({
      niveau: 'fin',
      periode: 0,
      numero: 0,
      reference: '',
      titre: ''
    })
  }

  function MAJLignesSequencesNormales () {
    const lignes = [] as Ligne[]
    for (const niveau of $niveauxSequences) {
      lignes.push({
        niveau: niveau.nom,
        reference: '',
        titre: '',
        periode: 0,
        numero: 0
      })
      for (const sequence of niveau.sequences) {
        lignes.push({
          niveau: niveau.nom,
          reference: sequence.reference,
          titre: sequence.titre,
          periode: sequence.periode,
          numero: sequence.numero
        })
      }
      lignes.push({
        niveau: 'fin',
        reference: '',
        titre: '',
        periode: 0,
        numero: 0
      })
    }
    lignesSequencesNormales.set(lignes)
  }

  function surveillerChargementDesDonnees () {
    sequencesParticulieresUnsubscribe = sequencesParticulieres.subscribe(() => MAJPage())
    niveauxSequencesUnsubscribe = niveauxSequences.subscribe(() => MAJPage())
    onDestroy(niveauxSequencesUnsubscribe)
    onDestroy(sequencesParticulieresUnsubscribe)
  }

  function getLignesFiltrees (texteRecherche: string, lignes: Ligne[]): Ligne[] {
    if (texteRecherche === '') return lignes
    const motsCherches = outils.normaliser(texteRecherche).split(' ')
    return lignes.filter((ligne) => {
      for (const mot of motsCherches) {
        if (!motTrouve(mot, ligne)) return false
      }
      return true
    })
  }

  function motTrouve (mot: string, ligne: Ligne) {
    if (
      ligne.niveau !== undefined &&
      outils.normaliser(ligne.niveau).includes(mot)
    ) { return true }
    if (
      ligne.numero !== undefined &&
      outils.normaliser(ligne.numero.toString()).includes(mot)
    ) { return true }
    if (
      ligne.reference !== undefined &&
      outils.normaliser(ligne.reference).includes(mot)
    ) { return true }
    if (
      ligne.titre !== undefined &&
      outils.normaliser(ligne.titre).includes(mot)
    ) { return true }
    return false
  }

  function clicFiltre (niveau: string, periode?: number) {
    if (niveau !== '') {
      ongletActif = niveau
      filtre.niveau = niveau
    }
    if (periode !== undefined) {
      filtre.periode === periode
        ? (filtre.periode = 0)
        : (filtre.periode = periode)
    }
  }
</script>

<svelte:head>
  <title>Liste des séquences - topmaths</title>
</svelte:head>

<div class="container is-max-desktop centre">
  <!-- Menu -->
  <div class="tabs is-medium is-centered">
    <ul class="tabs-menu is-rounded">
      <li>
        <button
          class="subtitle is-4 px-5 is-tout is-left-side"
          class:is-active={ongletActif === 'tout'}
          on:click={() => clicFiltre('tout')}>Tout</button
        >
      </li>
      {#each $lignesSequencesNormales as ligne}
        {#if ligne.niveau !== '' && ligne.niveau !== 'fin' && ligne.reference === ''}
          <li>
            <button
              on:click={() => clicFiltre(ligne.niveau)}
              class="subtitle is-4 px-5 is-{ligne.niveau}"
              class:is-active={ongletActif === ligne.niveau}
              class:is-right-side={ligne.niveau === '3e'}>{ligne.niveau}</button
            >
          </li>
        {/if}
      {/each}
      <li />
    </ul>
  </div>
  <div class="is-flex is-justify-content-center" style="overflow:auto">
    <span
      ><button
        class="button is-rounded is-link mb-5 mx-1 is-medium"
        class:is-light={filtre.periode !== null &&
          filtre.periode !== undefined &&
          filtre.periode > 0}
        on:click={() => clicFiltre('', 0)}>Période</button
      ></span
    >
    {#each [1, 2, 3, 4, 5] as periode}
      <span>
        <button
          class="button is-rounded is-link mb-5 mx-1 is-medium"
          class:is-light={filtre.periode !== periode}
          on:click={() => clicFiltre('', periode)}>{periode}</button
        >
      </span>
    {/each}
  </div>
  <input
    class="p-1"
    style="text-align:center; font-size:x-large;"
    type="text"
    aria-describedby="Champ pour rechercher une séquence"
    autocomplete="off"
    placeholder="Recherche"
    bind:value={$texteRecherche}
    on:input
  />
  <div><br /></div>
  <div class="container is-max-desktop centre">
    <!-- Séquences particulières -->
    {#if $texteRecherche === ''}
      <div>
        {#each lignesSequencesParticulieres as ligne, i}
          {#if ligne.niveau !== '' && ligne.niveau !== 'fin' && ligne.reference === ''}
            <h1 class="title is-3 p-2 mb-0 is-tout">{ligne.niveau}</h1>
          {/if}
          {#if ligne.reference !== ''}
            <a
              href="/?v=sequence&ref={ligne.reference}"
              on:click={(event) =>
                outils.go(event, 'sequence', ligne.reference)}
            >
              <div
                class="p-1 is-tout is-size-5"
                class:is-fin={i === lignesSequencesParticulieres.length - 2}
              >
                {ligne.numero === 0
                  ? ''
                  : 'Séquence ' + ligne.numero + ' : '}{ligne.titre}<br />
              </div>
            </a>
          {/if}
        {/each}
      </div>
      <div><br /></div>
    {/if}
    {#each $lignesFiltreesSequencesNormales as ligne, i}
      <div>
        {#if ligne.niveau !== '' && ligne.niveau !== 'fin' && ligne.reference === '' && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)}
          <h1 class="title is-3 p-2 is-{ligne.niveau}">
            <span class="has-text-white">
              {ligne.niveau}
            </span>
          </h1>
        {/if}
        {#if ligne.reference !== '' && ligne.niveau !== 'fin' && (ligne.periode === filtre.periode || filtre.periode === 0) && (filtre.niveau === 'tout' || filtre.niveau === ligne.niveau)}
          <div
            class="p-1 is-{ligne.niveau} is-size-5"
            class:is-fin={i < $lignesSequencesNormales.length && ((filtre.periode > 0 && $lignesSequencesNormales[i].periode !== $lignesSequencesNormales[i + 1].periode) || $lignesSequencesNormales[i + 1].niveau === 'fin')}
          >
            <a
              href="/?v=sequence&ref={ligne.reference}"
              on:click={(event) =>
                outils.go(event, 'sequence', ligne.reference)}
            >
              <div>
                {ligne.numero === 0
                  ? ''
                  : 'Séquence ' + ligne.numero + ' : '}{ligne.titre}
              </div>
            </a>
          </div>
        {/if}
      </div>
      {#if ligne.niveau === 'fin' && (filtre.niveau === 'tout')}
        <div><br /></div>
      {/if}
    {/each}
  </div>
</div>
