// src/app/sequencesParticulieres/sps1/sps1.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-sps1',
  templateUrl: './sps1.component.html',
  styleUrls: ['./sps1.component.css']
})
export class SPS1Component {
  seances: string[]

  constructor () {
    this.seances = [
      'Séquences d\'instructions',
      'Boucles simples',
      'Boucles à motif',
      'Boucles imbriquées',
      'Conditions',
      'Variables',
      'Boucles conditionnelles',
      'Procédures']
  }

}

<div class="container is-max-desktop centre">
  <h1 class="title is-2 is-tout">Programmation</h1>
  <div class="is-tout is-fin">
    <h2 class="mb-5 py-3 subtitle is-3 is-tout">Initiation : Lightbot Hour</h2>
    <img src="/assets/img/sps1/lightbot.png" width="200px"><br>
    <div class="columns is-centered is-vcentered">
      <a href='https://play.google.com/store/apps/details?id=com.lightbot.lightbothoc&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1' style="display: inline-block; overflow: hidden; border-radius: 13px; width: 320px;">
        <img alt='Disponible sur Google Play' src='https://play.google.com/intl/en_us/badges/static/images/badges/fr_badge_web_generic.png' style="border-radius: 13px; width: 320px;" />
      </a>
      <a href="https://apps.apple.com/us/app/lightbot-code-hour/id873943739?itsct=apps_box_badge&amp;itscg=30200" style="display: inline-block; overflow: hidden; border-radius: 13px; width: 250px;">
        <img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/fr-fr?size=250x83&amp;releaseDate=1399507200&h=3048f79da1f98cd11c6a5412485c29d2" alt="Download on the App Store" style="border-radius: 13px; width: 250px;">
      </a>
    </div>
    <p class="is-size-7">Google Play and the Google Play logo are trademarks of Google LLC. &nbsp; App Store and the App Store logo are trademarks of Apple Inc.</p>
    <div *ngFor="let seance of seances; index as i">
      <h2 class="my-5 py-3 subtitle is-3 is-tout">Séance {{ i + 1 }} : Algorea - {{ seance }}</h2>
      <a [href]="'https://concours.castor-informatique.fr/?team=seriousg' + (i + 1)">
        <img [src]="'assets/img/sps1/seance_seriousgame_0' + (i + 1) + '.png'">
      </a>
    </div>
    <div><br><br></div>
  </div>
</div>

// src/topmaths/components/sequences/SPS1.svelte
<script lang="ts">
  const seances = [
    "Séquences d'instructions",
    'Boucles simples',
    'Boucles à motif',
    'Boucles imbriquées',
    'Conditions',
    'Variables',
    'Boucles conditionnelles',
    'Procédures'
  ]
</script>

<svelte:head>
  <title>SPS1 : Programmation</title>
</svelte:head>

<div class="container is-max-desktop centre">
  <h1 class="title is-2 is-tout mb-0">Programmation</h1>
  <div class="is-tout is-fin">
    <h2 class="mb-5 py-3 subtitle is-3 is-tout">Initiation : Lightbot Hour</h2>
    <img class="is-inline-block" src="/assets/topmaths/img/sps1/lightbot.png" width="200px" alt="Logo de l'application Lightbot Hour"/><br /><br />
    <div class="columns is-centered is-vcentered">
      <a
        href="https://play.google.com/store/apps/details?id=com.lightbot.lightbothoc&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1"
        style="display: inline-block; overflow: hidden; border-radius: 13px; width: 320px;"
      >
        <img
          alt="Disponible sur Google Play"
          src="https://play.google.com/intl/en_us/badges/static/images/badges/fr_badge_web_generic.png"
          style="border-radius: 13px; width: 320px;"
        />
      </a>
      <a
        href="https://apps.apple.com/us/app/lightbot-code-hour/id873943739?itsct=apps_box_badge&amp;itscg=30200"
        style="display: inline-block; overflow: hidden; border-radius: 13px; width: 250px;"
      >
        <img
          src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/fr-fr?size=250x83&amp;releaseDate=1399507200&h=3048f79da1f98cd11c6a5412485c29d2"
          alt="Download on the App Store"
          style="border-radius: 13px; width: 250px;"
        />
      </a>
    </div>
    <p class="is-size-7">
      Google Play and the Google Play logo are trademarks of Google LLC. &nbsp;
      App Store and the App Store logo are trademarks of Apple Inc.
    </p>
    <div>
      <a href="https://concours.castor-informatique.fr/?">
        <h2 class="my-5 py-3 subtitle is-3 is-tout">
          Continuer une séance Algorea
        </h2>
      </a>
      <p>
        Il y a eu un bug ? Tu as eu un problème de connexion ?<br />
        Ou tu veux juste continuer à la maison la séance que tu as commencée en classe
        ?<br />
        Si tu as bien noté ton code, tu peux reprendre là où tu en étais grâce à
        ce bouton :<br /><br />
        <a href="https://concours.castor-informatique.fr/?"
          ><button class="button is-link is-large"
            >Continuer une séance Algorea</button
          ></a
        >
      </p>
    </div>
    {#each seances as seance, i}
      <div>
        <a href="https://concours.castor-informatique.fr/?team=seriousg{i + 1}">
          <h2 class="my-5 py-3 subtitle is-3 is-tout">
            Séance {i + 1} : Algorea - {seance}
          </h2>
          <img class="is-inline-block"
            src="assets/topmaths/img/sps1/seance_seriousgame_0{i + 1}.png"
            alt="Capture d'écran de la séance {i + 1} d'Algoréa"
          />
        </a>
      </div>
    {/each}
    <div><br /><br /></div>
  </div>
</div>
