// src/topmaths/components/Accueil.svelte
<script lang="ts">
  import { outils } from '../services/outils'
  import { onMount } from 'svelte'

  onMount(() => {
    window.scrollTo({
      top: 0
    })
  })

  function go (vue: string) {
    outils.goVue(vue)
  }
</script>

<svelte:head>
  <title>topmaths.fr - Les maths au TOP !</title>
</svelte:head>

<div class="container is-max-desktop centre">
  <button on:click={() => go('sequences')} class="button is-large is-info-darker is-outlined p-6">
    <p class="enorme">Séquences</p>
    &nbsp;
    <i class="image is-48x48 is-inline-block">
      <img src="assets/topmaths/img/cc0/guest-book-svgrepo-com.svg" alt="Livre ouvert" />
    </i>
  </button>
  <br />
  <br />
  <button on:click={() => go('objectifs')} class="button is-large is-link is-outlined p-6">
    <p class="enorme">Objectifs</p>
    &nbsp;
    <i class="image is-48x48 is-inline-block">
      <img src="assets/topmaths/img/cc0/study-2-svgrepo-com.svg" alt="Personne lisant un livre" />
    </i>
  </button>
  <br />
  <br />
  <button on:click={() => go('revisions')} class="button is-large is-sponsor is-outlined p-6">
    <p class="enorme">Révisions</p>
    &nbsp;
    <i class="image is-48x48 is-inline-block">
      <img src="assets/topmaths/img/gvalmont/automatismes-regular.svg" alt="Tête avec un engrenage à l'intérieur" />
    </i>
  </button>
  <br />
  <br />
  <button on:click={() => go('eleves')} class="button is-large is-purple is-outlined p-6">
    <p class="enorme">Outils pour<br />les élèves</p>
    &nbsp;
    <i class="image is-48x48 is-inline-block">
      <img src="assets/topmaths/img/cc0/backpack-svgrepo-com.svg" alt="Sac à dos d'élève" />
    </i>
  </button>
  <br />
  <br />
  <button on:click={() => go('outils')} class="button is-large is-green is-outlined p-6">
    <p class="enorme">Outils pour<br />la classe</p>
    &nbsp;
    <i class="image is-48x48 is-inline-block">
      <img src="assets/topmaths/img/cc0/classroom-svgrepo-com.svg" alt="Enseignant montrant un tableau face à une classe" />
    </i>
  </button>
</div>

// src/app/accueil/accueil.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-accueil',
  templateUrl: './accueil.component.html',
  styleUrls: []
})
export class AccueilComponent {

  constructor() {
  }
}

<div class="container is-max-desktop centre">
  <a [routerLink]="['/sequences/tout']">
    <button class="button is-large is-link is-outlined p-6">
      <p class="enorme">Séquences</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/cc0/guest-book-svgrepo-com.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <!-- <a [routerLink]="['/modules/tout']">
      <button class="button is-large is-fuchsia is-outlined p-6">
        <p class="enorme">Modules</p>
        &nbsp;
        <i class="image is-48x48 is-inline-block"><img src="assets/img/gvalmont/modules-regular.svg" /></i>
      </button>
    </a>
    <br>
    <br> -->
  <a [routerLink]="['/objectifs/tout']">
    <button class="button is-large is-info is-outlined p-6">
      <p class="enorme">Automatismes</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/gvalmont/automatismes-regular.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <a [routerLink]="['/revisions']">
    <button class="button is-large is-danger is-outlined p-6">
      <p class="enorme">Révisions</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/gvalmont/revisions-regular.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <!-- <a [routerLink]="['/objectifs/tout']">
      <button class="button is-large is-info is-outlined p-6">
        <p class="enorme">Objectifs</p>
        &nbsp;
        <i class="image is-48x48 is-inline-block"><img src="assets/img/cc0/dart-board-svgrepo-com.svg" /></i>
      </button>
    </a>
    <br>
    <br> -->
  <a [routerLink]="['/exercices-au-hasard']">
    <button class="button is-large is-sponsor is-outlined p-6">
      <p class="enorme">Exercices<br>au hasard</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/cc0/dice-svgrepo-com.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <a [routerLink]="['/competitions']">
    <button class="button is-large is-primary is-outlined p-6">
      <p class="enorme">Compétitions</p>
      &nbsp;
      <i class="image is-48x48"><img src="assets/img/cc0/games-podium-with-trophy-for-number-one-svgrepo-com.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <a [routerLink]="['/jeux']">
    <button class="button is-large is-success is-outlined p-6">
      <p class="enorme">Jeux</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/cc0/gamepad-retro-f-svgrepo-com.svg" /></i>
    </button>
  </a>
  <br>
  <br>
  <a [routerLink]="['/outils']">
    <button class="button is-large is-green is-outlined p-6">
      <p class="enorme">Outils pour<br>la classe</p>
      &nbsp;
      <i class="image is-48x48 is-inline-block"><img src="assets/img/cc0/classroom-svgrepo-com.svg" /></i>
    </button>
  </a>
</div>
